navsat_transform_node:
  ros__parameters:

    frequency: 30.0
    use_odometry_yaw: true
    wait_for_datum: false
    zero_altitude: true

    broadcast_utm_transform: true
    publish_filtered_gps: true

    magnetic_declination_radians: 0.0
    yaw_offset: 0.0

