planner_server:
  ros__parameters:
    use_sim_time: false
    plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

controller_server:
  ros__parameters:
    controller_frequency: 30.0
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      
      cmd_vel_topic: /cmd_vel
      odom_topic: /odom
      map_frame: map
      robot_base_frame: base_link

      time_steps: 56
      model_dt: 0.05
      batch_size: 1500
      iteration_count: 1

      temperature: 0.3
      gamma: 0.015
      reset_period: 1.0
      regenerate_noises: false
      visualize: false

      motion_model: "DiffDrive"   # Ackermann après

      vx_max: 0.6
      vx_min: 0.0         # pas de marche arrière 
      wz_max: 1.2

      ax_max: 2.0
      ax_min: -2.0

      # Pas de déplacement latéral (voiture)
      vy_max: 0.0
      vy_std: 0.0

      vx_std: 0.2
      wz_std: 0.3

      AckermannConstraints:
        min_turning_r: 1.5

      TrajectoryValidator:
        plugin: "mppi::DefaultOptimalTrajectoryValidator"
        collision_lookahead_time: 1.5
        consider_footprint: true

      critics:
        [
          "ConstraintCritic",
          "GoalCritic",
          "GoalAngleCritic",
          "PathAlignCritic",
          "PathFollowCritic",
          "PathAngleCritic",
          "PreferForwardCritic"
        ]

      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0

      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 6.0
        threshold_to_consider: 1.2

      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
        threshold_to_consider: 0.4

      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 6.0
        threshold_to_consider: 0.3

      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 14.0
        trajectory_point_step: 4
        threshold_to_consider: 0.5
        offset_from_furthest: 15
        use_path_orientations: false

      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 6.0
        threshold_to_consider: 1.2
        offset_from_furthest: 6

      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5
        offset_from_furthest: 4
        max_angle_to_furthest: 1.0
        mode: 0
      
bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link

behavior_server:
  ros__parameters:
    use_sim_time: false

waypoint_follower:
  ros__parameters:
    use_sim_time: false

velocity_smoother:
  ros__parameters:
    use_sim_time: false

